# Generated by Django 5.2.9 on 2026-04-27 11:36

import django.db.models.deletion
import mainapp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CATEGORIE_CLIENT',
            },
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=50)),
                ('code_devise', models.IntegerField()),
                ('cours_devise', models.FloatField()),
            ],
            options={
                'db_table': 'DEVISE',
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('bp_etablissement', models.CharField(blank=True, max_length=10, null=True)),
                ('tx_commission', models.PositiveIntegerField()),
                ('tx_tax', models.PositiveIntegerField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('plafond_commission', models.PositiveIntegerField()),
                ('tx_commission2', models.PositiveIntegerField()),
                ('tx_commission3', models.PositiveIntegerField()),
                ('min_commission', models.PositiveIntegerField()),
                ('tx_retro', models.PositiveIntegerField()),
                ('mt_retro', models.PositiveIntegerField()),
                ('signe_etablissement', models.CharField(blank=True, max_length=20, null=True)),
                ('min_retro', models.PositiveIntegerField()),
                ('orgaprinc', models.BooleanField(default=False)),
                ('orga_fin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ETABLISSEMENT',
            },
        ),
        migrations.CreateModel(
            name='Qualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'QUALITE',
            },
        ),
        migrations.CreateModel(
            name='TypeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=50, unique=True)),
                ('mvnt_operation', models.CharField(max_length=50)),
                ('commission', models.FloatField()),
                ('tva', models.FloatField()),
                ('rcm', models.FloatField()),
                ('css', models.FloatField()),
            ],
            options={
                'db_table': 'TYPE_OPERATION',
            },
        ),
        migrations.CreateModel(
            name='TypePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'TYPEPIECE',
            },
        ),
        migrations.CreateModel(
            name='TypeTitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TYPE_TITRE',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('nom_client', models.CharField(max_length=100)),
                ('prenom_client', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('bp_client', models.CharField(blank=True, max_length=10, null=True)),
                ('tel_client', models.CharField(blank=True, max_length=15, null=True)),
                ('fax_client', models.CharField(blank=True, max_length=20, null=True)),
                ('tx_commission', models.FloatField(default=0.0)),
                ('exonerer_taxe', models.BooleanField(default=False)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=200)),
                ('num_carte', models.CharField(max_length=30)),
                ('matricule', models.CharField(max_length=20)),
                ('email_client', models.EmailField(max_length=50)),
                ('site_client', models.CharField(blank=True, max_length=100, null=True)),
                ('ca_code', models.BooleanField(default=True)),
                ('indentifiant', models.IntegerField()),
                ('category_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.categorieclient')),
            ],
            options={
                'db_table': 'CLIENT',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('num_ordre', models.IntegerField()),
                ('num_seq_ordre', models.IntegerField()),
                ('nb_titre', models.IntegerField()),
                ('cours_operation', models.IntegerField()),
                ('date_ordre', models.DateField()),
                ('montant', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.client')),
            ],
            options={
                'db_table': 'OPERATION',
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('indicatif_pays', models.CharField(max_length=8)),
                ('nom_pays', models.CharField(max_length=7, unique=True)),
                ('devise_pays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.devise')),
            ],
            options={
                'db_table': 'Pays',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.pays'),
        ),
        migrations.AddField(
            model_name='client',
            name='qualite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.qualite'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.typepiece'),
        ),
        migrations.CreateModel(
            name='Titre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=100)),
                ('nominal', models.IntegerField()),
                ('quotite', models.IntegerField()),
                ('nb_mini', models.IntegerField()),
                ('cours', models.IntegerField()),
                ('cours_oblig', models.IntegerField()),
                ('tx_oblig', models.IntegerField()),
                ('logo', models.ImageField(upload_to='')),
                ('dercoupon', models.DateField()),
                ('min_ann', models.IntegerField()),
                ('max_ann', models.IntegerField()),
                ('nb_actions', models.IntegerField()),
                ('date_inf', models.DateField()),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.devise')),
                ('type_titre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.typetitre')),
            ],
            options={
                'db_table': 'Titre',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', mainapp.models.UserManager()),
            ],
        ),
    ]
