# Generated by Django 5.2.9 on 2026-04-28 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_compte_portefeuil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Histo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.client')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.operation')),
            ],
            options={
                'db_table': 'HISTORIQUE',
            },
        ),
    ]
