# Generated by Django 5.2.9 on 2026-06-16 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_client_qualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='portefeuille',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.etablissement'),
        ),
    ]
