# Generated by Django 5.2.9 on 2026-05-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_histo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='min_commission',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='mt_retro',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='tx_commission2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='tx_commission3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='tx_retro',
            field=models.FloatField(),
        ),
    ]
