# Generated by Django 5.2.9 on 2026-06-16 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_portefeuille_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portefeuille',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.etablissement'),
        ),
    ]
