# Generated by Django 5.2.9 on 2026-06-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_portefeuille_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='portefeuille',
            name='dernier_mouv',
            field=models.DateField(blank=True, null=True),
        ),
    ]
