# Generated by Django 5.2.9 on 2026-06-16 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_portefeuille_dernier_mouv'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='banque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.etablissement'),
        ),
    ]
