# Generated by Django 5.2.9 on 2026-06-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_client_banque'),
    ]

    operations = [
        migrations.AddField(
            model_name='indextitre',
            name='indordre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
