# Generated by Django 5.2.9 on 2026-06-17 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_indextitre_indordre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indextitre',
            name='portef_client',
        ),
        migrations.RemoveField(
            model_name='nantis',
            name='portef_client',
        ),
        migrations.AddField(
            model_name='indextitre',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.client'),
        ),
        migrations.AddField(
            model_name='indextitre',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.etablissement'),
        ),
        migrations.AddField(
            model_name='indextitre',
            name='nb_titre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indextitre',
            name='titre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.titre'),
        ),
        migrations.AlterField(
            model_name='indextitre',
            name='statut_tire',
            field=models.IntegerField(default=1),
        ),
    ]
