# Generated by Django 5.2.9 on 2026-06-17 14:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_indextitre_portef_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('date_creat', models.DateField(blank=True, null=True)),
                ('date_modif', models.DateField(blank=True, null=True)),
                ('nom_creat', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_modif', models.CharField(blank=True, max_length=100, null=True)),
                ('code_cat', models.CharField(max_length=5)),
                ('libelle_cat', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'CATEGORIE_ACTION',
            },
        ),
    ]
