# Generated by Django 5.2.9 on 2026-06-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_categorieaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieaction',
            name='libelle_cat',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
