# Generated by Django 5.2.9 on 2026-06-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_categorieaction_libelle_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devise',
            name='code_devise',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='devise',
            name='libelle',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
