# Generated by Django 5.2.9 on 2026-06-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_devise_code_devise_alter_devise_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titre',
            name='tx_oblig',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
