# Generated by Django 5.2.9 on 2026-06-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_titre_tx_oblig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titre',
            name='date_inf',
            field=models.DateField(blank=True, null=True),
        ),
    ]
