# Generated by Django 5.2.9 on 2026-06-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_titre_date_inf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='prenom_client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
