# Generated by Django 5.2.9 on 2026-06-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_client_prenom_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
