# Generated by Django 5.2.9 on 2026-06-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_client_lieu_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nationalite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
