# Generated by Django 5.2.9 on 2026-06-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_client_nationalite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='num_carte',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
