# Generated by Django 5.2.9 on 2026-06-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_client_matricule_alter_client_num_carte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ca_code',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
