# Generated by Django 5.2.9 on 2026-07-02 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='beneficiaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beneficiaires', to='mainapp.client'),
        ),
        migrations.AddField(
            model_name='operation',
            name='commission',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operation',
            name='css',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.etablissement'),
        ),
        migrations.AddField(
            model_name='operation',
            name='ircm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='ordre_ben',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='ordre_valide',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='sens',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='tax',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operation',
            name='titre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.titre'),
        ),
        migrations.AddField(
            model_name='operation',
            name='type_titre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.typetitre'),
        ),
    ]
