# Generated by Django 5.2.9 on 2026-07-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_operation_beneficiaire_operation_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='brut',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='code_op',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='code_op_ben',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='nbencours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='nbportef',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='nbportefben',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='old_id_ben',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='old_id_ets_ben',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='old_id_sous_ben',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='commission',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='css',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='ircm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='montant',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='nom_creat',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='nom_modif',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='num_seq_ordre',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='operation',
            name='tax',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
