# Generated by Django 5.2.9 on 2026-07-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_operation_brut_operation_code_op_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='css',
        ),
    ]
