# Generated by Django 5.2.9 on 2026-07-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_remove_operation_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='css',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
    ]
