# Generated by Django 5.2.9 on 2026-07-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_operation_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='css',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
