# Generated by Django 5.2.9 on 2026-07-07 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_alter_operation_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.etablissement'),
        ),
        migrations.AddField(
            model_name='compte',
            name='num_compte',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
