# Generated by Django 5.2.9 on 2026-07-07 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_compte_etablissement_compte_num_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='etablissement_ben',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ets_ben', to='mainapp.etablissement'),
        ),
    ]
