# Generated by Django 5.2.9 on 2026-07-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_operation_etablissement_ben'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='tot_nbportebef',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
