# Generated by Django 5.2.9 on 2026-07-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_operation_tot_nbportebef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date_ordre',
            field=models.DateField(blank=True, null=True),
        ),
    ]
