# Generated by Django 5.2.9 on 2026-07-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_alter_operation_date_ordre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='css',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
