# Generated by Django 5.2.9 on 2026-07-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_alter_operation_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='est_valide',
            field=models.BooleanField(default=False),
        ),
    ]
