# Generated by Django 5.2.9 on 2026-07-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_operation_est_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='type_op',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
