# Generated by Django 5.2.9 on 2026-07-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_operation_type_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='num_seq_ordre',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
