# Generated by Django 5.2.9 on 2026-07-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_alter_operation_num_seq_ordre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='type_op',
        ),
        migrations.AddField(
            model_name='operation',
            name='type_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.typeoperation'),
        ),
    ]
