# Generated by Django 5.2.9 on 2026-07-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_remove_operation_type_op_operation_type_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='num_seq_ordre',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
