# Generated by Django 5.2.9 on 2026-07-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_alter_operation_num_seq_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
