# Generated by Django 5.2.9 on 2026-07-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_user_created_by_user_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indextitre',
            name='nb_titre',
        ),
    ]
