# Generated by Django 5.2.9 on 2026-07-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_remove_indextitre_nb_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email_client',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
