# Generated by Django 5.2.9 on 2026-07-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_alter_client_email_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titre',
            name='nb_actions',
        ),
    ]
