# Generated by Django 5.2.9 on 2026-07-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_remove_titre_nb_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieclient',
            name='nom_creat',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='categorieclient',
            name='nom_modif',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
