# Generated by Django 5.2.9 on 2026-07-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_alter_categorieclient_nom_creat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typetitre',
            name='nom_creat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='typetitre',
            name='nom_modif',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
