# Generated by Django 5.2.9 on 2026-07-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_alter_typetitre_nom_creat_alter_typetitre_nom_modif'),
    ]

    operations = [
        migrations.AddField(
            model_name='titre',
            name='nb_actions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
