# Generated by Django 5.2.9 on 2026-07-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_titre_nb_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bp_client',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel_client',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
