# Generated by Django 5.2.9 on 2026-07-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_alter_client_bp_client_alter_client_tel_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='ordre_valide',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
