# Generated by Django 5.2.9 on 2026-07-22 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_alter_operation_ordre_valide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.client'),
        ),
    ]
