# Generated by Django 5.2.9 on 2026-07-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_alter_operation_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'managed': False, 'permissions': [('imp_avis_transaction', 'Peut imprimer avis de transaction')]},
        ),
    ]
