# Generated by Django 5.2.9 on 2026-08-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_alter_operation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='Opérateur', max_length=20),
        ),
    ]
