# Generated by Django 5.2.9 on 2026-08-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Opérateur', 'Opérateur'), ('Administrateur', 'Administrateur')], default='Opérateur', max_length=20),
        ),
    ]
