# Generated by Django 5.2.9 on 2026-08-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'managed': False, 'permissions': [('imp_avis_transaction', 'Peut imprimer avis de transaction'), ('valider_operation', 'Peut valider une opération')]},
        ),
    ]
