# Generated by Django 5.2.9 on 2026-08-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_alter_operation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'managed': False, 'permissions': [('imprimer_doc', 'Peut imprimer un document'), ('valider_operation', 'Peut valider une opération')]},
        ),
    ]
