# Generated by Django 5.2.9 on 2026-08-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0051_alter_operation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceCertificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dernier_numero', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Séquence de certificat',
                'verbose_name_plural': 'Séquences de certificat',
            },
        ),
    ]
