# Generated by Django 5.2.9 on 2026-08-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0052_sequencecertificat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceOrdre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dernier_numero', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Séquence ordre',
                'verbose_name_plural': 'Séquences ordre',
                'db_table': 'SEQUENCE_ORDRE',
            },
        ),
        migrations.AlterModelTable(
            name='sequencecertificat',
            table='SEQUENCE_CERTIFICAT',
        ),
    ]
